// Precompiles src/AntiAFKNative.cpp -> src/AntiAFKNative.exe using MSVC (cl.exe) or GCC (g++).
// Runs automatically before `npm run build` (npm "prebuild" lifecycle) so a
// prebuilt C++ native helper ships inside the app.

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const src = path.join(__dirname, '..', 'src', 'AntiAFKNative.cpp');
const out = path.join(__dirname, '..', 'src', 'AntiAFKNative.exe');

function findCompiler() {
  // Check cl.exe (MSVC) in PATH
  try {
    const clTest = spawnSync('where', ['cl.exe'], { encoding: 'utf8', windowsHide: true });
    if (clTest.status === 0 && clTest.stdout.trim()) {
      return { type: 'cl', cmd: 'cl.exe' };
    }
  } catch {}

  // Check g++ in PATH
  try {
    const gppTest = spawnSync('where', ['g++.exe'], { encoding: 'utf8', windowsHide: true });
    if (gppTest.status === 0 && gppTest.stdout.trim()) {
      return { type: 'g++', cmd: 'g++.exe' };
    }
  } catch {}

  // Check common MinGW / GCC installation paths
  const gccCandidates = [
    'C:\\msys64\\ucrt64\\bin\\g++.exe',
    'C:\\msys64\\mingw64\\bin\\g++.exe',
    'C:\\MinGW\\bin\\g++.exe',
    'C:\\TDM-GCC-64\\bin\\g++.exe',
    'C:\\mingw64\\bin\\g++.exe',
  ];
  for (const c of gccCandidates) {
    if (fs.existsSync(c)) return { type: 'g++', cmd: c };
  }

  // Check Visual Studio vcvarsall / vcvars64 paths dynamically
  const programFiles86 = process.env['ProgramFiles(x86)'] || 'C:\\Program Files (x86)';
  const programFiles = process.env['ProgramFiles'] || 'C:\\Program Files';

  for (const pf of [programFiles, programFiles86]) {
    const vsRoot = path.join(pf, 'Microsoft Visual Studio');
    if (!fs.existsSync(vsRoot)) continue;

    try {
      const years = fs.readdirSync(vsRoot);
      for (const year of years) {
        const yearDir = path.join(vsRoot, year);
        if (!fs.statSync(yearDir).isDirectory()) continue;
        const editions = fs.readdirSync(yearDir);
        for (const ed of editions) {
          const edDir = path.join(yearDir, ed);
          if (!fs.statSync(edDir).isDirectory()) continue;

          const vcvars64 = path.join(edDir, 'VC', 'Auxiliary', 'Build', 'vcvars64.bat');
          if (fs.existsSync(vcvars64)) return { type: 'vcvars64', cmd: vcvars64 };

          const vcvarsall = path.join(edDir, 'VC', 'Auxiliary', 'Build', 'vcvarsall.bat');
          if (fs.existsSync(vcvarsall)) return { type: 'vcvarsall', cmd: vcvarsall };
        }
      }
    } catch {}
  }

  return null;
}

if (process.platform !== 'win32') {
  console.log('[build-native] non-Windows host; skipping precompile.');
  process.exit(0);
}

if (!fs.existsSync(src)) {
  console.warn('[build-native] src/AntiAFKNative.cpp not found; skipping.');
  process.exit(0);
}

const compiler = findCompiler();
if (!compiler) {
  console.warn('[build-native] C++ compiler (cl.exe / g++) not found; skipping precompile.');
  process.exit(0);
}

console.log(`[build-native] compiling AntiAFKNative.exe using ${compiler.type} ...`);
let r;

if (compiler.type === 'cl') {
  r = spawnSync(compiler.cmd, [
    '/nologo', '/O2', '/EHsc', '/std:c++17',
    '/Fe:' + out, src,
    'winmm.lib', 'ole32.lib', 'oleaut32.lib'
  ], { stdio: 'inherit', cwd: path.dirname(src) });

  // Clean up object files generated by cl
  const objFile = path.join(__dirname, '..', 'src', 'AntiAFKNative.obj');
  try { if (fs.existsSync(objFile)) fs.unlinkSync(objFile); } catch {}
} else if (compiler.type === 'vcvars64' || compiler.type === 'vcvarsall') {
  const { execSync } = require('child_process');
  const batCmd = (compiler.type === 'vcvarsall') ? `"${compiler.cmd}" x64` : `"${compiler.cmd}"`;
  const fullCmd = `call ${batCmd} && cl /nologo /O2 /EHsc /std:c++17 /Fe:"${out}" "${src}" winmm.lib ole32.lib oleaut32.lib`;
  try {
    execSync(fullCmd, { stdio: 'inherit', cwd: path.dirname(src) });
    r = { status: 0 };
  } catch (e) {
    r = { status: e.status || 1 };
  }
  const objFile = path.join(__dirname, '..', 'src', 'AntiAFKNative.obj');
  try { if (fs.existsSync(objFile)) fs.unlinkSync(objFile); } catch {}
} else if (compiler.type === 'g++') {
  r = spawnSync(compiler.cmd, [
    '-O3', '-std=c++17', '-o', out, src,
    '-lwinmm', '-lole32', '-loleaut32'
  ], { stdio: 'inherit', cwd: path.dirname(src) });
}

if (r && r.status === 0 && fs.existsSync(out)) {
  console.log('[build-native] done ->', out);
} else {
  console.warn('[build-native] compile failed; exit code ' + (r ? r.status : 'unknown'));
}
process.exit(0);
