const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  minimize: () => ipcRenderer.send('window-minimize'),
  maximize: () => ipcRenderer.send('window-maximize'),
  close: () => ipcRenderer.send('window-close'),
  loadAccounts: () => ipcRenderer.invoke('accounts:load'),
  addAccount: (a) => ipcRenderer.invoke('accounts:add', a),
  removeAccount: (id) => ipcRenderer.invoke('accounts:remove', id),
  updateAccount: (id, data) => ipcRenderer.invoke('accounts:update', id, data),
  reorderAccounts: (ids) => ipcRenderer.invoke('accounts:reorder', ids),
  loadPackages: () => ipcRenderer.invoke('packages:load'),
  savePackages: (packages) => ipcRenderer.invoke('packages:save', packages),
  openLogin: (bounds) => ipcRenderer.invoke('roblox:openLogin', bounds),
  updateLoginBounds: (bounds) => ipcRenderer.invoke('roblox:updateLoginBounds', bounds),
  hideLoginView: () => ipcRenderer.invoke('roblox:hideLoginView'),
  cancelLogin: () => ipcRenderer.send('login:cancel'),
  onLoginError: (cb) => ipcRenderer.on('login:load-error', (_, data) => cb(data)),
  validateCookie: (cookie) => ipcRenderer.invoke('roblox:validateCookie', cookie),
  setRobloxVolume: (percent, pid) => ipcRenderer.invoke('roblox:setVolume', percent, pid),
  killAllRoblox: () => ipcRenderer.invoke('roblox:killAll'),
  killOneRoblox: (id) => ipcRenderer.invoke('roblox:killOne', id),
  getRunningCount: () => ipcRenderer.invoke('roblox:runningCount'),
  onAllRobloxClosed: (cb) => ipcRenderer.on('roblox:allClosed', () => cb()),
  launchRoblox: (id, cookie, target) => ipcRenderer.invoke('roblox:launch', id, cookie, target),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  loadSettings: () => ipcRenderer.invoke('settings:load'),
  saveSettings: (data) => ipcRenderer.invoke('settings:save', data),
  encStatus: () => ipcRenderer.invoke('enc:status'),
  encUnlock: (pass, remember) => ipcRenderer.invoke('enc:unlock', pass, remember),
  encSetKey: (pass, remember) => ipcRenderer.invoke('enc:setKey', pass, remember),
  multiInstanceStatus: () => ipcRenderer.invoke('multiinstance:status'),
  antiAfkStatus: () => ipcRenderer.invoke('antiafk:status'),
  readGenHistory: () => ipcRenderer.invoke('genhistory:read'),
  writeGenHistory: (list) => ipcRenderer.invoke('genhistory:write', list),
  clearGenHistory: () => ipcRenderer.invoke('genhistory:clear'),
  readFFlags: () => ipcRenderer.invoke('fflag:read'),
  writeFFlags: (flags) => ipcRenderer.invoke('fflag:write', flags),
  readFpsCap: () => ipcRenderer.invoke('fps:read'),
  writeFpsCap: (cap) => ipcRenderer.invoke('fps:write', cap),
  onChromeProgress: (cb) => ipcRenderer.on('chrome:download-progress', (_, data) => cb(data)),
  onRobloxClosed: (cb) => ipcRenderer.on('roblox:closed', (_, id) => cb(id)),
  onRobloxCount: (cb) => ipcRenderer.on('roblox:count', (_, n) => cb(n)),
  onLogEntry: (cb) => ipcRenderer.on('log:entry', (_, data) => cb(data)),
  getRobloxVersion: () => ipcRenderer.invoke('roblox:getVersion'),
  getGameName: (placeId, cookie) => ipcRenderer.invoke('roblox:getGameName', placeId, cookie),
  getAuthenticatedJson: (hostname, path, cookie) => ipcRenderer.invoke('roblox:getAuthenticatedJson', hostname, path, cookie),
  fetchPublicJson: (url) => ipcRenderer.invoke('roblox:fetchPublicJson', url),
  getSystemStatus: () => ipcRenderer.invoke('system:status'),
  setAlwaysOnTop: (flag) => ipcRenderer.invoke('window:setAlwaysOnTop', flag),
  copyToClipboard: (text) => ipcRenderer.invoke('clipboard:writeText', text),
  gridSnap: () => ipcRenderer.invoke('native:grid'),
  showAllRoblox: () => ipcRenderer.invoke('native:showall'),
  hideAllRoblox: () => ipcRenderer.invoke('native:hideall'),
  setWindowOpacity: (pct) => ipcRenderer.invoke('native:opacity', pct),
  setDoNotSleep: (enable) => ipcRenderer.invoke('native:dosleep', enable),
  resetAllRoblox: () => ipcRenderer.invoke('native:resetall'),
  testAntiAfkAction: (actionType) => ipcRenderer.invoke('native:testaction', actionType),
  testDiscordWebhook: () => ipcRenderer.invoke('discord:test'),
  downloadRobloxVersion: (hash) => ipcRenderer.invoke('roblox:downloadVersion', hash),
  onInstallProgress: (cb) => ipcRenderer.on('roblox:install-progress', (_, data) => cb(data)),
  captureRobloxPosition: (accountId) => ipcRenderer.invoke('roblox:capture-position', accountId),
  getPrimaryWorkArea: () => ipcRenderer.invoke('screen:primary-workarea'),
  snapActiveRobloxGrid: () => ipcRenderer.invoke('roblox:snap-grid'),
  openHome: (accountId) => ipcRenderer.invoke('home:open', accountId),
  hideHome: () => ipcRenderer.invoke('home:hide'),
  resizeHome: (bounds) => ipcRenderer.invoke('home:resize', bounds),
  homeGoBack: () => ipcRenderer.invoke('home:go-back'),
  homeGoForward: () => ipcRenderer.invoke('home:go-forward'),
  homeReload: () => ipcRenderer.invoke('home:reload'),
  onHomeUrlUpdated: (cb) => ipcRenderer.on('home:url-updated', (_, url) => cb(url)),
  showHomeAccountMenu: (rect) => ipcRenderer.invoke('home:show-account-menu', rect),
  openHomeAccountPopup: (data) => ipcRenderer.invoke('home:open-account-popup', data),
  closeHomeAccountPopup: () => ipcRenderer.invoke('home:close-account-popup'),
  selectHomeAccountFromPopup: (id) => ipcRenderer.send('home:account-selected-from-popup', id),
  onHomeAccountSelected: (cb) => ipcRenderer.on('home:account-selected', (_, id) => cb(id)),
  onHomeAccountPopupClosed: (cb) => ipcRenderer.on('home:account-popup-closed', () => cb()),
  onAccountUpdated: (cb) => ipcRenderer.on('accounts:updated', (_, account) => cb(account)),
  prepareHomeSession: (accountId) => ipcRenderer.invoke('home:prepare-session', accountId),
  checkReconnectNow: () => ipcRenderer.invoke('native:reconnectcheck'),
  getVoidstrapStatus: () => ipcRenderer.invoke('voidstrap:status'),
  openVoidstrapFolder: (type) => ipcRenderer.invoke('voidstrap:open-folder', type),
  readVoidstrapPresets: () => ipcRenderer.invoke('voidstrap:read-presets'),
  applyVoidstrapPresets: (presets) => ipcRenderer.invoke('voidstrap:apply-presets', presets),
  getVoidstrapProfiles: () => ipcRenderer.invoke('voidstrap:get-profiles'),
  saveVoidstrapProfile: (name, data) => ipcRenderer.invoke('voidstrap:save-profile', name, data),
  deleteVoidstrapProfile: (name) => ipcRenderer.invoke('voidstrap:delete-profile', name),
  exportVoidstrapProfile: (name) => ipcRenderer.invoke('voidstrap:export-profile', name),
  importVoidstrapProfile: () => ipcRenderer.invoke('voidstrap:import-profile'),
  deleteFFlag: (flag) => ipcRenderer.invoke('fflag:delete', flag),
  setRawFFlags: (jsonStr) => ipcRenderer.invoke('fflag:set-raw', jsonStr),
  getModSettings: () => ipcRenderer.invoke('mods:get-settings'),
  saveModSettings: (settings) => ipcRenderer.invoke('mods:save-settings', settings),
  pickModFile: (category) => ipcRenderer.invoke('mods:pick-file', category),
  deployMods: () => ipcRenderer.invoke('mods:deploy'),
  openModsFolder: () => ipcRenderer.invoke('mods:open-folder'),
  getDiscordRpcStatus: () => ipcRenderer.invoke('discord:rpc-status'),
  setDiscordRpc: (enable, options) => ipcRenderer.invoke('discord:rpc-set', enable, options),
  getDiscordRpcSettings: () => ipcRenderer.invoke('discord:rpc-get-settings'),
  saveDiscordRpcSettings: (settings) => ipcRenderer.invoke('discord:rpc-save-settings', settings),
  testDiscordRpc: () => ipcRenderer.invoke('discord:rpc-test'),
});
